<?php $pageTitle = 'VAMC Medical Gas Utility Project'; ?>
<?php include('inc/header.php') ?>

    <!--=== Container Part ===-->
    <div class="container content">

        <div class="margin-bottom-40">
            <h1>Microsoft CRM Implementation </h1>
        </div>

        <div class="margin-bottom-60 lead">

            <img src="assets/img/comcentia-recent-projects/dept-agriculture-wi-logo-lg.jpg" class="pull-right img-reponsive">

            <h2>Project Scope:</h2>
            <p>DATCP (Wisconsin Department of Agriculture, Trade and Consumer Protection) is using Microsoft CRM (Customer Relationships Management) software to obtain information, track the information, use the information for licensing businesses to perform various services, handle complaints, schedule compliance actions (inspections, etc.) in the agribusiness industry. It also uses this software to track information and schedule inspections regarding Consumer Protection (scales are accurate, gas pumps are accurate, etc.), and handle the Registries and Lists section of the system (e.g. lists of people certified to apply pesticides, etc.).</p>

            <h2>Comcentia Involvement:</h2>
            <p>Comcentia consultant is working with an internal team to develop an external facing front end to the services and functionality created within Microsoft CRM.</p>       
        </div>

        <div class="margin-bottom-60 well">
            <h3>Project Details</h3>
            <p><strong>Client:</strong> Department of Agriculture, Trade and Consumer Protection, State of Wisconsin</p>
            <p><strong>COMPLETION DATE:</strong> Ongoing</p>
               
        </div>
    </div>

<?php include('inc/footer.php') ?>